import { layoutLayer } from "./layout";

export function clearRectAndPaintLayer(e, p) {
  this.canvasUtils.clearRect(e.x0, e.y0, e.x1 - e.x0, e.y1 - e.y0);
  this.paintLayer([e], p);
}

const autoGeneratedColorCache = new WeakMap();

function genColor() {
  const colors = [
    "#00B3A4",
    "#3185FC",
    "#DB1374",
    "#490092",
    "#FEB6DB",
    "#F98510",
    "#E6C220",
    "#BFA180",
    "#920000",
    "#461A0A",
  ];
  return colors[Math.floor(Math.random() * colors.length)];
}

function autoGenerateColor(item) {
  if (autoGeneratedColorCache.has(item)) {
    return autoGeneratedColorCache.get(item);
  }

  const c = genColor();
  const color = ({ ctx, bounds }) => {
    if ((bounds.y0 || bounds.y0 === 0) && (bounds.y1 || bounds.y1 === 0)) {
      const gradient = ctx.createLinearGradient(0, bounds.y1, 0, bounds.y0);
      gradient.addColorStop(0, c + "FF");
      gradient.addColorStop(1, c + "AA");
      return gradient;
    }
    return c;
  };
  autoGeneratedColorCache.set(item, color);

  return color;
}

/**
 * low-level api to actually draw to the canvas.
 * will be called multiple times during a transition
 */
export function paintLayer(data, { hovering, transitionProgress = 0, depth }) {
  if (!data || depth > 2) {
    return;
  }

  for (let item of data) {
    let bounds = this.viewportUtils.transform({
      x0: item.x0,
      y0: item.y0,
      x1: item.x1,
      y1: item.y1,
    });

    let itemColor;
    try {
      itemColor = (item.color || autoGenerateColor(item))({
        hovering,
        ctx: this.canvas2dContext,
        bounds,
        item,
      });
    } catch (error) {
      console.warn("TreeBox could not resolve an item color", error);
      itemColor = autoGenerateColor(item)({
        hovering,
        ctx: this.canvas2dContext,
        bounds,
        item,
      });
    }

    const fontSizeCss = Math.min(
      Math.round((bounds.x1 - bounds.x0) / this.pixelRatio / 10),
      Math.round((bounds.y1 - bounds.y0) / this.pixelRatio / 3),
      160
    );
    const fontSize = fontSizeCss * this.pixelRatio;

    const doPaintNode = () => {
      try {
        if (hovering) {
          this.canvas2dContext.save();
          this.canvas2dContext.filter = "brightness(110%) saturate(120%)";
          this.canvas2dContext.globalAlpha = 0.6;
        }
        this.canvasUtils.fillRect(
          item.x0,
          item.y0,
          item.x1 - item.x0,
          item.y1 - item.y0,
          {
            color: itemColor,
          }
        );

        if (hovering) {
          this.canvas2dContext.restore();
        }
      } catch (e) {
        console.warn(e);
      }

      if (depth <= 2) {
        this.canvasUtils.fillText(item.text, bounds, fontSize);
      }
    };

    if (item.children) {
      this.paintLayer(item.children, {
        hovering,
        transitionProgress,
        depth: depth + 1,
      });
      if (this.transitionTargetNode === item) {
        this.canvas2dContext.save();
        this.canvas2dContext.globalAlpha = 1 - transitionProgress;
        this.canvasUtils.fillRect(
          item.x0,
          item.y0,
          item.x1 - item.x0,
          item.y1 - item.y0,
          {
            color: itemColor,
          }
        );
        if (depth <= 2) {
          this.canvasUtils.fillText(item.text, bounds, fontSize, "#FFFFFF");
        }
        this.canvas2dContext.restore();
      } else {
        if (this.activeNode !== item) {
          doPaintNode();
        }
      }
    } else {
      this.canvasUtils.clearRect(
        item.x0,
        item.y0,
        item.x1 - item.x0,
        item.y1 - item.y0
      );
      doPaintNode();
    }
  }
}

function syncCanvasDimensions() {
  const width = this.domElement.clientWidth;
  const height = this.domElement.clientHeight;
  this.canvasElement.width = Math.round(width * this.pixelRatio);
  this.canvasElement.height = Math.round(height * this.pixelRatio);
  this.canvasElement.style.width = width + "px";
  this.canvasElement.style.height = height + "px";
  this.domElementRect = this.canvasElement.getBoundingClientRect();
}

function scaleViewport(viewport, previousBounds, nextBounds) {
  const scaleX =
    (nextBounds.x1 - nextBounds.x0) / (previousBounds.x1 - previousBounds.x0);
  const scaleY =
    (nextBounds.y1 - nextBounds.y0) / (previousBounds.y1 - previousBounds.y0);
  return {
    x0: nextBounds.x0 + (viewport.x0 - previousBounds.x0) * scaleX,
    x1: nextBounds.x0 + (viewport.x1 - previousBounds.x0) * scaleX,
    y0: nextBounds.y0 + (viewport.y0 - previousBounds.y0) * scaleY,
    y1: nextBounds.y0 + (viewport.y1 - previousBounds.y0) * scaleY,
  };
}

function viewportBounds(viewport) {
  return {
    x0: viewport.x0,
    x1: viewport.x1,
    y0: viewport.y0,
    y1: viewport.y1,
  };
}

export function resize() {
  if (this.destroyed) {
    return false;
  }

  const width = this.domElement.clientWidth;
  const height = this.domElement.clientHeight;
  const previousBounds = {
    x0: this.rootNode.x0,
    x1: this.rootNode.x1,
    y0: this.rootNode.y0,
    y1: this.rootNode.y1,
  };
  const nextBounds = { x0: 0, x1: width, y0: 0, y1: height };

  const sizeChanged =
    previousBounds.x1 !== nextBounds.x1 || previousBounds.y1 !== nextBounds.y1;
  if (sizeChanged && this.isMouseDown) {
    this.onPointerCancelEventListener({ pointerId: this.activePointerId });
    // The physical release can still synthesize a click even though TreeBox
    // canceled its stale coordinates. Consume that click instead of zooming.
    this.selectionAreaWasTriggered = true;
  }

  if (width <= 0 || height <= 0) {
    syncCanvasDimensions.call(this);
    return false;
  }

  if (
    previousBounds.x1 === nextBounds.x1 &&
    previousBounds.y1 === nextBounds.y1
  ) {
    this.repaint({ skipResize: true });
    return false;
  }

  if (this.viewportTransitionInProgress) {
    this.resizePending = true;
    this.repaint({ skipResize: true });
    return false;
  }

  const scaledViewports = new Set();
  for (const entry of [
    ...this.viewportHistory,
    ...this.viewportHistoryUndoStack,
  ]) {
    if (entry.viewport !== entry.node && !scaledViewports.has(entry.viewport)) {
      Object.assign(
        entry.viewport,
        scaleViewport(entry.viewport, previousBounds, nextBounds)
      );
      scaledViewports.add(entry.viewport);
    }
  }

  Object.assign(this.rootNode, nextBounds, { w: width, h: height });
  layoutLayer(this.rootNode.children, { ...nextBounds, depth: 0 });

  const currentEntry = this.viewportHistory[this.viewportHistory.length - 1];
  Object.assign(
    this.viewport,
    viewportBounds(currentEntry ? currentEntry.viewport : nextBounds)
  );
  if (this.lastHoveringItem) {
    this.emitEvent("hover", null);
    this.lastHoveringItem = null;
  }
  this.lastMousePos = null;
  this.canvasElement.style.cursor = "default";
  this.repaint({ skipResize: true });
  this.emitEvent("resize", { width, height });
  return true;
}

export function repaint({ skipResize = false } = {}) {
  if (this.destroyed) {
    return;
  }

  if (
    !skipResize &&
    (this.rootNode.x1 !== this.domElement.clientWidth ||
      this.rootNode.y1 !== this.domElement.clientHeight)
  ) {
    return this.resize();
  }

  syncCanvasDimensions.call(this);

  if (this.domElement.clientWidth <= 0 || this.domElement.clientHeight <= 0) {
    return;
  }

  this.clearRectAndPaintLayer(this.activeNode, { hovering: false, depth: -1 });
}
